# Railway Configuration
[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments]

[environments.production]
[environments.production.variables]
NODE_ENV = "production"

# Healthcheck configuration
[[environments.production.healthcheck]]
path = "/health"
timeout = 10
interval = 30

# Build optimization
[build.nixpacksConfig]
providers = ["nodejs"]

[build.nixpacksConfig.nodejs]
version = "18"

# Database migration on deploy
[[build.buildPhases]]
name = "Database Migration"
dependsOn = ["install"]
cmds = ["npx prisma generate", "npx prisma migrate deploy"]